-- Insert sample users
INSERT INTO users (username, hashed_password, role) VALUES ('admin', '$2b$10$example.hash.for.admin.password', 'admin');
INSERT INTO users (username, hashed_password, role) VALUES ('analyst', '$2b$10$example.hash.for.analyst.password', 'user');

-- Insert sample report configurations
INSERT INTO report_configurations (label, query_template, column_definitions, parameter_definitions) VALUES ('Portfolio Summary', 'SELECT ACCT, NAME, ACTIVE FROM FRPAIR WHERE ACTIVE = ''Open''', '[{"name":"ACCT","type":"VARCHAR","label":"Account ID"},{"name":"NAME","type":"VARCHAR","label":"Account Name"},{"name":"ACTIVE","type":"VARCHAR","label":"Status"}]', '[]');
INSERT INTO report_configurations (label, query_template, column_definitions, parameter_definitions) VALUES ('Holdings Report', 'SELECT h.AACCT, h.HID, s.NAMETKR, h.HUNITS, h.HPRINCIPAL FROM FRPHOLD h JOIN FRPSEC s ON h.HID = s.ID WHERE h.AACCT = ?', '[{"name":"AACCT","type":"VARCHAR","label":"Account"},{"name":"HID","type":"VARCHAR","label":"Security ID"},{"name":"NAMETKR","type":"VARCHAR","label":"Security Name"},{"name":"HUNITS","type":"DOUBLE","label":"Units"},{"name":"HPRINCIPAL","type":"DOUBLE","label":"Market Value"}]', '[{"name":"account_id","type":"VARCHAR","label":"Account ID","required":true}]');
INSERT INTO report_configurations (label, query_template, column_definitions, parameter_definitions) VALUES ('Transaction History', 'SELECT t.AACCT, t.TDATE, t.TCODE, s.NAMETKR, t.TUNITS, t.TPRINCIPAL FROM FRPTRAN t JOIN FRPSEC s ON t.HID = s.ID WHERE t.AACCT = ? ORDER BY t.TDATE DESC', '[{"name":"AACCT","type":"VARCHAR","label":"Account"},{"name":"TDATE","type":"DATE","label":"Date"},{"name":"TCODE","type":"VARCHAR","label":"Transaction Type"},{"name":"NAMETKR","type":"VARCHAR","label":"Security"},{"name":"TUNITS","type":"DOUBLE","label":"Units"},{"name":"TPRINCIPAL","type":"DOUBLE","label":"Amount"}]', '[{"name":"account_id","type":"VARCHAR","label":"Account ID","required":true}]');

-- Insert sample workflows
INSERT INTO agentic_workflows (name, description, workflow_data, status) VALUES ('Daily Portfolio Analysis', 'Automated daily analysis of portfolio performance and risk metrics', '{"steps":[{"type":"data_collection","query":"SELECT * FROM FRPHOLD WHERE ADATE = CURRENT_DATE"},{"type":"calculation","metric":"portfolio_value"},{"type":"risk_analysis","method":"var_calculation"},{"type":"report_generation","template":"daily_summary"}],"schedule":"daily","notifications":["admin@example.com"]}', 'active');
INSERT INTO agentic_workflows (name, description, workflow_data, status) VALUES ('Monthly Performance Review', 'Monthly portfolio performance analysis and benchmarking', '{"steps":[{"type":"data_collection","query":"SELECT * FROM FRPTRAN WHERE TDATE >= DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH)"},{"type":"performance_calculation","benchmark":"SP500"},{"type":"comparison_analysis","period":"month"},{"type":"report_generation","template":"monthly_performance"}],"schedule":"monthly","notifications":["admin@example.com","analyst@example.com"]}', 'active');
